# Generated by Django 3.0.5 on 2020-04-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200422_1728'),
        ('posts', '0002_auto_20200422_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='profiles.Profile'),
        ),
    ]
