# Generated by Django 3.0.5 on 2020-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200422_1549'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='posts.Post'),
        ),
    ]
